apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: weather-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts", "pods", "nodes"]
  verbs: ["get"]
  resourceNames: ["weather-secret" , "elasticsearch-master-credentials"]
