apiVersion: v2
name: weather-app
description: A Helm chart for the Weather App
type: application
version: 0.2.0
appVersion: "1.0"

dependencies:
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
#  - name: kibana
#    version: 8.5.1
#    repository: https://helm.elastic.co
